### ISSUE TITLE
server can't find baike.baidu.com: NXDOMAIN

### ISSUE THREAD

**Issue by caidaoli** [Lafeng/dnspanic#2]
nslookup                                                                                                 
> server 127.0.0.1
Default server: 127.0.0.1
Address: 127.0.0.1#53
> set debug
> baike.baidu.com
Server:		127.0.0.1
Address:	127.0.0.1#53

------------
    QUESTIONS:
	baike.baidu.com, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ADDITIONAL RECORDS:
------------
** server can't find baike.baidu.com: SERVFAIL
Server:		127.0.0.1
Address:	127.0.0.1#53

------------
    QUESTIONS:
	baike.baidu.com.lan, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  .
	origin = a.root-servers.net
	mail addr = nstld.verisign-grs.com
	serial = 2016051801
	refresh = 1800
	retry = 900
	expire = 604800
	minimum = 86400
	ttl = 10616
    ADDITIONAL RECORDS:
------------
** server can't find baike.baidu.com: NXDOMAIN

2016/05/19 12:56:30.559511 Query [baike.baidu.com.lan. A] @udp://114.114.114.114:53 rtt=7 answers=0
2016/05/19 12:56:30.933823 Query [baike.baidu.com.lan. A] @udp://223.5.5.5:53 rtt=3 answers=0
2016/05/19 12:56:31.034382 Query [baike.baidu.com.lan. A] @tcp://202.141.162.123:53 rtt=455 answers=0

**Comment by vickery** [comment]
Obviously, you're querying [baike.baidu.com.lan], not the [baike.baidu.com].

**Comment by caidaoli** [comment]
` nslookup                                                                                                 
> server 127.0.0.1
Default server: 127.0.0.1
Address: 127.0.0.1#53
> baike.baidu.com
Server:		127.0.0.1
Address:	127.0.0.1#53

** server can't find baike.baidu.com: NXDOMAIN
`
this is my conf
`# Backend Syntax:
# <backend_name> = [ <backend_item>, ... ]
# <backend_item> := "PROTO://ADDRESS[:PORT]"
###
backends {
    default = [
        "udp://114.114.114.114",
        "tcp://202.141.162.123",
        "udp://223.5.5.5",
        "udp://[2620:0:ccd::2]",
        "tcp://[2001:470:20::2]",
        "udp://208.67.220.220:5353",
    ]

    secondary = [
        "udp://[2620:0:ccd::2]",
        "tcp://[2001:470:20::2]",
        "udp://8.8.4.4",
        "udp://208.67.220.220:5353",
        "tcp://202.141.162.123",
    ]

    faraway = [
        "udp://[2620:0:ccd::2]",
        "tcp://[2001:470:20::2]",
        "udp://4.2.2.4",
        "udp://74.82.42.42",
        "tcp://202.141.162.123",
    ]

    apple = [
        "udp://202.101.172.35",
        "udp://115.159.97.97",
        "udp://114.114.114.114",
        "tcp://202.141.162.123",
    ]
}

# Prefilters Syntax:
# <filter_name> {
#                  disabled = [ <disabled_item>, ... ]
#               }
# <disabled_item> := "IP_ADDRESS" | "@file_name"
###
prefilters {
    disabled = ["@ads.list"]
}

# Filter Syntax:
# <filter_name> {
#                   drop    = [ <dropping_item>, ... ]      # optional
#                   replace = [ <replacement_item>, ... ]   # optional
#               }
# <dropping_item> := "IP_ADDRESS" | "@file_name"
# <replacement_item> := "IP_ADDRESS_A/IP_ADDRESS_B"
###
filters {
    default {
        drop = ["@black.list"]
    }

    # replace this address of github cdn to another, then could avoid tcp reset
    github_fastly {
        replace = ["103.245.222.133/23.235.44.133"]
    }
}

# Domain Syntax:
# <domain> {
#             backends = [ <backend_name>, ... ]  # optional
#             filters  = [ <filter_name>, ... ]   # optional
#          }
# <domain> := "domain.tld [, domain.tld] ... "
# <backend_name> := "a name of backend referenced to backends.someone"
# <filter_name>  := "a name of filter referenced to filters.someone"
###
domains {
    # explicitly use some special backends for the below domains
    "cloudfront.net, dropbox.com, dropboxusercontent.com, amazonaws.com, live.com, wikipedia.org, gravatar.com" {
        backends = ["secondary"]
    }

    "edgecastcdn.net, googleapis.com, github.com, githubusercontent.com" {
        backends = ["secondary"]
    }

    # want got some faraway addresses of this domains from some faraway backends
    fastly.net {
        backends = ["faraway"]
    }

    "cloudfront.net, cdn-apple.com, anquan.io, apple.com, mzstatic.com, akadns.net, ourwebcdn.com, ccgslb.net,alicdn.com, taobao.com, mmstat.com, ccgslb.com.cn, ourglb0.com" {
        backends = ["apple"]
    }
}
`

**Comment by vickery** [comment]
First, you'd better make the code looks clear and clean.
Capture the command output of `dig some-domain.com` (http://www.isc.org/downloads/) and dnspanic logs, then paste it here.
If you have installed wireshark, please capture the udp packets between dns client and dnspanic.

**Comment by caidaoli** [comment]
sorry , is my problem
